stages:
  - test
  - build

docker_build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - cd apps/backend
    - docker login -u johncosta27 -p $DOCKER_TOKEN
    - docker build -f Auth.Dockerfile -t johncosta27/fyp-auth .
    - docker push johncosta27/fyp-auth
    - docker build -f Brain.Dockerfile -t johncosta27/fyp-brain .
    - docker push johncosta27/fyp-brain
    - docker build -f Hub.Dockerfile -t johncosta27/fyp-hub .
    - docker push johncosta27/fyp-hub

integration_tests:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - cd apps/backend
    - docker-compose up --build
    - cd ../integration
    - npm ci
    - npm run test:clean