# Production file.
# Not for local development
# The big difference is that the images are pulled from the docker hub
# and not from local images, allowing for easy replacement as needed.

version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.11.2-management
    ports:
      - 15672:15672 #Management console
      - 5672:5672 #Actual exchange
    network_mode: host
    restart: on-failure

  brain_postgres:
    image: postgres:15
    volumes:
      - ./brain_postgres/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./brain_postgres/db:/var/lib/postgresql/data
    environment:
      POSTGRES_NAME: ${BRAIN_DB_NAME}
      POSTGRES_USER: ${BRAIN_DB_USER}
      POSTGRES_PASSWORD: ${BRAIN_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
    ports:
      - 5443:5432

  auth:
    build: 
      context: .
      dockerfile: ./Auth.Dockerfile
    ports:
      - 4546:4546
    depends_on: 
      - brain_postgres
      - auth_postgres
    restart: on-failure
    network_mode: host

  auth_postgres:
    build: ./auth_postgres
    volumes:
      - ./auth_postgres/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./auth_postgres/db:/var/lib/postgresql/data
    environment:
      POSTGRES_NAME: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
    ports:
      - 5442:5432
